networks:
  iti:
    external: true

services:
  linguaquest-backend:
    container_name: team8-linguaquest-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - iti
    volumes:
      - ./logs:/app/logs
    mem_limit: 2g
    mem_reservation: 1g
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /team8
      JAVA_OPTS: "-XX:+UseG1GC -Xms512m -Xmx1024m -XX:+UseContainerSupport"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.team8-backend.rule=PathPrefix(`/team8`)"
      - "traefik.http.services.team8-backend.loadbalancer.server.port=8080"
      - "traefik.docker.network=iti"
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle-team8
    environment:
      DOZZLE_BASE: /team8-logs
      DOZZLE_BASE_PATH: /team8-logs
      DOZZLE_FILTER: "name=team8"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - iti
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.team8-dozzle.rule=PathPrefix(`/team8-logs`)"
      - "traefik.http.services.team8-dozzle.loadbalancer.server.port=8080"
      - "traefik.docker.network=iti"
    restart: unless-stopped

