package gov.jets.iti.LinguaQuest.ai.tripleai.dto.response;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Immutable DTO representing a successful chat or multimodal chat response from the Gateway.
 *
 * @param requestId        unique identifier for the Gateway request
 * @param modelId          executed Gateway model identifier
 * @param region           execution region (e.g. "us-east-1")
 * @param outputText       the text generated by the model
 * @param usage            token consumption statistics
 * @param estimatedCostUsd estimated cost in USD
 * @param actualCostUsd    actual cost in USD
 * @param status           execution status (e.g. "active")
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GatewayChatResponse(
        @JsonProperty("request_id") String requestId,
        @JsonProperty("model_id") String modelId,
        @JsonProperty("region") String region,
        @JsonProperty("output_text") String outputText,
        @JsonProperty("usage") GatewayUsage usage,
        @JsonProperty("estimated_cost_usd") String estimatedCostUsd,
        @JsonProperty("actual_cost_usd") String actualCostUsd,
        @JsonProperty("status") String status
) {
}
